import pandas as pd
import numpy as np
import sys

df1 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\NPF_yes_no.csv')
df2 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2014_AWS.csv')
df3 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2014_chem.csv')
df4 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2014_chem_3.csv')
df5 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2021 AWS.csv')
df6 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2016.Gwangju.Sp.airkorea_KORUS.csv')
df7 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2016.Gwangju.Sp.aws_KORUS.csv')
df8 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2015.Gwangju.Sp.airkorea_MAPS.csv')
df9 = pd.read_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\2015.Gwangju.Sp.aws_MAPS.csv')

df1['date'] = pd.to_datetime(df1['date']).dt.strftime('%Y/%m/%d')
df1 = df1.sort_values(by='date')
df1 = df1.drop(columns=['coverage'])
df1 = df1.dropna()

df2['date'] = pd.to_datetime(df2['date']).dt.strftime('%Y/%m/%d')
df2 = df2.sort_values(by='date')
df2 = df2[['date', 'temperature', 'RH', 'pressure', 'SRAD']].copy()
df2 = df2.dropna()
df2 = df2.groupby('date').mean()
df2 = df2.reset_index()


df3['date'] = pd.to_datetime(df3['date']).dt.strftime('%Y/%m/%d')
df3 = df3.sort_values(by='date')
df3 = df3[['date', 'pm10', 'so2']].copy()
df3 = df3.dropna()
df3 = df3.groupby('date').mean()
df3 = df3.reset_index()

df4['date'] = pd.to_datetime(df4['date']).dt.strftime('%Y/%m/%d')
df4 = df4[['date', 'temperature', 'RH', 'pressure', 'SRAD', 'pm10', 'so2']].copy()
df4 = df4.groupby('date').mean()
df4 = df4.sort_values(by='date')
df4 = df4.dropna()
df4 = df4.reset_index()

df5['date'] = pd.to_datetime(df5['date']).dt.strftime('%Y/%m/%d')
df5 = df5[['date', 'temperature', 'RH', 'pressure', 'SRAD', 'pm10', 'so2']].copy()
df5 = df5.groupby('date').mean()
df5 = df5.sort_values(by='date')
df5 = df5.dropna()
df5 = df5.reset_index()

df6['date'] = pd.to_datetime(df6['date']).dt.strftime('%Y/%m/%d')
df6 = df6[['date', 'pm10', 'so2']].copy()
df6 = df6.groupby('date').mean()
df6 = df6.sort_values(by='date')
df6 = df6.dropna()
df6 = df6.reset_index()

df7['date'] = pd.to_datetime(df7['date']).dt.strftime('%Y/%m/%d')
df7 = df7[['date', 'temperature', 'RH', 'pressure', 'SRAD']].copy()
df7 = df7.groupby('date').mean()
df7 = df7.sort_values(by='date')
df7 = df7.dropna()
df7 = df7.reset_index()

df8['date'] = pd.to_datetime(df8['date']).dt.strftime('%Y/%m/%d')
df8 = df8[['date','pm10', 'so2']].copy()
df8 = df8.groupby('date').mean()
df8 = df8.sort_values(by='date')
df8 = df8.dropna()
df8 = df8.reset_index()

df9['date'] = pd.to_datetime(df9['date']).dt.strftime('%Y/%m/%d')
df9 = df9[['date', 'temperature', 'RH', 'pressure', 'SRAD']].copy()
df9 = df9.groupby('date').mean()
df9 = df9.sort_values(by='date')
df9 = df9.dropna()
df9 = df9.reset_index()

df1['date'] = pd.to_datetime(df1['date']).dt.strftime('%Y/%m/%d')
df2['date'] = pd.to_datetime(df2['date']).dt.strftime('%Y/%m/%d')
df3['date'] = pd.to_datetime(df3['date']).dt.strftime('%Y/%m/%d')
df4['date'] = pd.to_datetime(df4['date']).dt.strftime('%Y/%m/%d')
df5['date'] = pd.to_datetime(df5['date']).dt.strftime('%Y/%m/%d')
df6['date'] = pd.to_datetime(df6['date']).dt.strftime('%Y/%m/%d')
df7['date'] = pd.to_datetime(df7['date']).dt.strftime('%Y/%m/%d')
df8['date'] = pd.to_datetime(df8['date']).dt.strftime('%Y/%m/%d')
df9['date'] = pd.to_datetime(df9['date']).dt.strftime('%Y/%m/%d')

result = pd.merge(df1, df2, how='outer', on='date')
result = pd.merge(result, df3, how='outer', on='date')
result.fillna(df4, inplace=True)
result.fillna(df5, inplace=True)
result = pd.merge(result, df5, how='outer', on='date', suffixes=('', '_delme'))
result = pd.merge(result, df7, how='outer', on='date', suffixes=('', '_delme'))
result = pd.merge(result, df6, how='outer', on='date', suffixes=('', '_delme'))
result = pd.merge(result, df9, how='outer', on='date', suffixes=('', '_delme'))
result = pd.merge(result, df8, how='outer', on='date', suffixes=('', '_delme'))
result.to_csv(r'C:\\Users\\Masloriy\\Desktop\\Data_urban\\dodo\\csv\\output_combined_2.csv')